import http from"node:http";import{readFile,stat}from"node:fs/promises";import{extname,join,normalize}from"node:path";
const root=process.cwd(),port=Number(process.env.PORT||3000),MAX=4*1024*1024;
const mime={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".svg":"image/svg+xml"};
const send=(res,code,obj)=>{res.writeHead(code,{"content-type":"application/json; charset=utf-8"});res.end(JSON.stringify(obj))};
async function body(req){let n=0,ch=[];for await(const c of req){n+=c.length;if(n>MAX)throw Object.assign(new Error("payload too large"),{status:413});ch.push(c)}return ch.length?JSON.parse(Buffer.concat(ch).toString("utf8")):{}}
const safePath=p=>typeof p==="string"&&p.length>0&&!p.startsWith("/")&&!p.includes("..")&&!p.includes("\\");
function validate(project={}){const files=Array.isArray(project.files)?project.files:[],spec=project.spec||{},e=[];const add=(name,status,detail)=>e.push({name,status,detail});
 add("File count",files.length>=8&&files.length<=200?"PASS":"FAIL",files.length+" files");
 const paths=files.map(f=>f?.path).filter(Boolean);add("Safe paths",paths.every(safePath)?"PASS":"FAIL","relative paths only");add("Unique paths",new Set(paths).size===paths.length?"PASS":"FAIL","no path collisions");
 const all=files.map(f=>String(f?.content||"")).join("\n");add("Credential scan",/(?:api[_-]?key|token|secret)\s*[:=]\s*["'][A-Za-z0-9_\-]{20,}/i.test(all)?"FAIL":"PASS","generic credential-pattern scan");
 const pkgs=files.filter(f=>/package\.json$/.test(f.path||""));let pkgOk=true;for(const f of pkgs)try{JSON.parse(f.content)}catch{pkgOk=false}add("package.json parse",pkgOk?"PASS":"FAIL",pkgs.length+" manifest(s)");
 add("Backend health",files.some(f=>/health/i.test((f.path||"")+" "+(f.content||"")))?"PASS":"FAIL","health endpoint/check");
 add("Tests",files.some(f=>/(test|spec)\.(js|ts|tsx|jsx)$|\/tests?\//i.test(f.path||""))?"PASS":"PARTIAL","automated test files");
 add("Database",files.some(f=>/(schema|migration|database|prisma|sql)/i.test(f.path||""))?"PASS":"PARTIAL","database artifact");
 add("Auth",files.some(f=>/(auth|session|login|security)/i.test((f.path||"")+" "+(f.content||"")))?"PASS":"PARTIAL","auth/security artifact");
 add("Deploy manifest",files.some(f=>f.path==="deploy.json")?"PASS":"PARTIAL","deploy.json");
 add("Acceptance",Array.isArray(spec.acceptance)&&spec.acceptance.length>=3?"PASS":"PARTIAL",(spec.acceptance?.length||0)+" criteria");
 const verdict=e.some(x=>x.status==="FAIL")?"FAIL":e.some(x=>x.status==="PARTIAL"||x.status==="UNVERIFIED")?"PARTIAL":"PASS";return{verdict,evidence:e,summary:verdict==="PASS"?"Server validation passed":"Server validation requires attention"}}
function deployPlan(project){const v=validate(project),files=project.files||[];const dynamic=files.some(f=>/^backend\//.test(f.path||""));return{status:v.verdict==="FAIL"?"FAIL":"PARTIAL",validation:v,target:dynamic?"container":"static-or-container",healthPath:dynamic?"/health":"/",requirements:{gitWrite:true,deployBroker:true,secretsBroker:true,databaseBroker:files.some(f=>/(schema|migration|database|sql)/i.test(f.path||""))},providers:[{id:"railway",status:"UNVERIFIED"},{id:"vercel",status:"UNVERIFIED"},{id:"netlify",status:"UNVERIFIED"}],note:"No provider is PASS until a real deployment broker returns public runtime evidence."}}
async function api(req,res,url){if(req.method==="GET"&&url.pathname==="/health")return send(res,200,{ok:true,service:"astra-builder-omega-v3",version:"3.0.0",broker:!!process.env.ASTRA_DEPLOY_BROKER_URL});
 if(req.method==="GET"&&url.pathname==="/api/self_test"){const sample={spec:{acceptance:["UI renders","API health works","Auth and data contracts exist"]},files:[{path:"frontend/index.html",content:"<main>ASTRA test</main>"},{path:"backend/package.json",content:'{"name":"demo","version":"1.0.0"}'},{path:"backend/src/server.js",content:"app.get('/health',handler)"},{path:"backend/tests/server.test.js",content:"test health endpoint"},{path:"database/schema.sql",content:"create table users(id text primary key);"},{path:"auth/session.js",content:"export function sessionGuard(){}"},{path:"deploy.json",content:'{"healthPath":"/health"}'},{path:"README.md",content:"demo"}]};const v=validate(sample);return send(res,v.verdict==="PASS"?200:500,{ok:v.verdict==="PASS",verdict:v.verdict,evidence:v.evidence})}
 if(req.method==="GET"&&url.pathname==="/api/capabilities")return send(res,200,{version:"3.0.0",serverValidation:true,deployBroker:!!process.env.ASTRA_DEPLOY_BROKER_URL,zeroCostGate:true,maxPayloadBytes:MAX});
 if(req.method==="POST"&&url.pathname==="/api/validate")return send(res,200,validate(await body(req)));
 if(req.method==="POST"&&url.pathname==="/api/deploy-plan")return send(res,200,deployPlan(await body(req)));
 if(req.method==="POST"&&url.pathname==="/api/deploy"){const project=await body(req),plan=deployPlan(project);if(plan.validation.verdict==="FAIL")return send(res,422,{status:"FAIL",plan});const broker=process.env.ASTRA_DEPLOY_BROKER_URL;if(!broker)return send(res,501,{status:"UNVERIFIED",reason:"No authorized deploy broker configured",plan});const headers={"content-type":"application/json"};if(process.env.ASTRA_BROKER_SECRET)headers.authorization="Bearer "+process.env.ASTRA_BROKER_SECRET;const r=await fetch(broker,{method:"POST",headers,body:JSON.stringify({project,plan})}),raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data={raw}}return send(res,r.ok?200:502,{status:r.ok?"PARTIAL":"FAIL",brokerStatus:r.status,data,plan})}
 return false}
const srv=http.createServer(async(req,res)=>{try{const url=new URL(req.url||"/","http://localhost");if(url.pathname.startsWith("/api/")||url.pathname==="/health"){const done=await api(req,res,url);if(done!==false)return}let p=decodeURIComponent(url.pathname);if(p==="/")p="/index.html";const rel=normalize(p).replace(/^[/\\]+/,"");if(!safePath(rel)){res.writeHead(403);return res.end("Forbidden")}const f=join(root,rel);if(!f.startsWith(root)){res.writeHead(403);return res.end("Forbidden")}const st=await stat(f);if(!st.isFile())throw new Error("not file");const data=await readFile(f);res.writeHead(200,{"content-type":mime[extname(f)]||"application/octet-stream","cache-control":"public,max-age=300"});res.end(data)}catch(e){if(e?.status)return send(res,e.status,{error:e.message});res.writeHead(404,{"content-type":"text/plain; charset=utf-8"});res.end("Not found")}});
srv.listen(port,"0.0.0.0",()=>console.log("ASTRA BUILDER Ω V3 listening",port));