import{chat,generateImage,effectiveModel,costStatus,normalizeBase}from"./router.js";
import{staticChecks,benchmark}from"./quality.js";
import{makeZip}from"./zip.js";
import{prompts}from"./prompts.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const phases=["SPEC","FRONTEND","BACKEND","OPS","IMAGES","STATIC TEST","ADVERSARY","REPAIR","VERIFY²"];
const defaults={baseUrl:"https://openrouter.ai/api/v1",apiKey:"",architect:"deepseek/deepseek-v3.2",frontend:"qwen/qwen3-coder-next",backend:"qwen/qwen3-coder-next",ops:"qwen/qwen3-coder-next",adversary:"deepseek/deepseek-v3.2",verifier:"qwen/qwen3.6-plus",imageBaseUrl:"",imageKey:"",imageModel:"black-forest-labs/FLUX.2-klein-4B",zeroCost:true,attestedFree:false};
const state={cfg:{...defaults},files:[],assets:[],spec:null,evidence:[],agents:{},status:"UNVERIFIED",selected:null,bench:null};
function parse(t){const c=(t||"").trim().replace(/^\`\`\`(?:json)?/i,"").replace(/\`\`\`$/i,"").trim();try{return JSON.parse(c)}catch{}const a=c.indexOf("{"),b=c.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(c.slice(a,b+1));throw new Error("Réponse IA non JSON")}
function safeFiles(v){return(v?.files||[]).filter(x=>x&&typeof x.path==="string"&&typeof x.content==="string"&&x.path&&!x.path.includes("..")&&!x.path.startsWith("/"))}
function mergeFiles(...groups){const m=new Map;for(const g of groups)for(const f of g)m.set(f.path,f);return[...m.values()].sort((a,b)=>a.path.localeCompare(b.path))}
function setStatus(s){state.status=s;const e=$("#globalStatus");e.textContent=s;e.className="badge "+s.toLowerCase()}
function setPhase(name){state.phase=name;renderPhases()}
function renderPhases(){const root=$("#phases");root.innerHTML=phases.map((p,i)=>`<div class="phase ${state.phase===p?"active":""}"><b>${i+1}</b><span>${p}</span><em>${state.phase===p?"RUNNING":state.phase==="DONE"?"DONE":"WAIT"}</em></div>`).join("")}
function agent(name,model,status="UNVERIFIED"){state.agents[name]={model,status};renderAgents()}
function renderAgents(){const r=$("#agents");r.innerHTML=Object.entries(state.agents).map(([n,a])=>`<div class="agent"><span>${n}</span><small>${a.model}</small><small class="${a.status.toLowerCase()}">${a.status}</small></div>`).join("")}
function addEv(name,status,detail){const i=state.evidence.findIndex(x=>x.name===name);const x={name,status,detail};if(i>=0)state.evidence[i]=x;else state.evidence.push(x);renderEvidence()}
function renderEvidence(){const r=$("#ledger");r.innerHTML=state.evidence.length?state.evidence.map(x=>`<div class="ev"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.detail)}</small></div><span class="${x.status.toLowerCase()}">${x.status}</span></div>`).join(""):'<p class="muted">Aucun contrôle exécuté.</p>';const p=state.evidence.filter(x=>x.status==="PASS").length;$("#score").textContent=p+"/"+state.evidence.length;$("#fileCount").textContent=state.files.length;$("#assetCount").textContent=state.assets.length;$("#testCount").textContent=state.files.filter(f=>/(test|spec)/i.test(f.path)).length;$("#deployReadiness").textContent=state.evidence.some(x=>x.status==="FAIL")?"FAIL":state.files.some(f=>f.path==="deploy.json")?"PARTIAL":"UNVERIFIED"}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function routeSummary(){const c=state.cfg;$("#routeSummary").innerHTML=`ZERO-COST GATE: <b>${c.zeroCost?"ON":"OFF"}</b><br>Text: ${escapeHtml(normalizeBase(c.baseUrl)||"—")}<br>Builder effectif: ${escapeHtml(effectiveModel(c,c.frontend))}<br>Text cost gate: <b>${costStatus(c,"text")}</b> · Image cost gate: <b>${costStatus(c,"image")}</b>`}
function renderFiles(){const tree=$("#fileTree");tree.innerHTML=state.files.map(f=>`<button data-path="${escapeHtml(f.path)}" class="${state.selected===f.path?"active":""}" title="${escapeHtml(f.path)}">${escapeHtml(f.path)}</button>`).join("");$$("#fileTree button").forEach(b=>b.onclick=()=>selectFile(b.dataset.path));$("#exportBtn").disabled=!state.files.length;renderEvidence()}
function selectFile(path){state.selected=path;const f=state.files.find(x=>x.path===path);$("#filePath").textContent=path||"—";$("#codeViewer").textContent=f?.content||"";$("#downloadFileBtn").disabled=!f;renderFiles()}
function previewDoc(){const m=Object.fromEntries(state.files.map(f=>[f.path,f.content]));let h=m["preview/index.html"]||"<html><body><h1>Preview absente</h1></body></html>";h=h.replace(/<link[^>]*href=["'](?:\.\/)?styles\.css["'][^>]*>/i,"<style>"+(m["preview/styles.css"]||"").replace(/<\/style/gi,"<\\/style")+"</style>");h=h.replace(/<script[^>]*src=["'](?:\.\/)?app\.js["'][^>]*><\/script>/i,"<script>"+(m["preview/app.js"]||"").replace(/<\/script/gi,"<\\/script")+"<\\/script>");for(const a of state.assets){h=h.replace(new RegExp(`(<img[^>]*data-astra-image=["']${a.id}["'][^>]*)(>)`,"gi"),`$1 src="${a.dataUrl}"$2`)}return h}
function renderPreview(){const f=$("#preview"),empty=$("#previewEmpty");if(state.files.some(x=>x.path==="preview/index.html")){f.style.display="block";empty.classList.add("hidden");f.srcdoc=previewDoc()}else{f.style.display="none";empty.classList.remove("hidden")}}
function renderSpec(){$("#specViewer").textContent=JSON.stringify(state.spec||{status:"waiting"},null,2)}
function renderBenchmark(){const b=state.bench;if(!b){$("#benchmarkView").innerHTML="<p>Aucun benchmark exécuté.</p>";return}$("#benchmarkView").innerHTML=`<div class="bench-grid"><div class="bench-card"><small>Evidence quality</small><b>${b.quality}%</b></div><div class="bench-card"><small>Completeness</small><b>${b.completeness}%</b></div><div class="bench-card"><small>Architecture</small><b>${b.architecture}%</b></div></div><table class="bench-table"><tr><th>Mesure</th><th>ASTRA</th><th>Lovable</th><th>Bolt</th></tr><tr><td>Files</td><td>${b.files}</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr><tr><td>Tests</td><td>${b.tests}</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr><tr><td>Résultat comparatif</td><td>Mesuré localement</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr></table><p class="muted">${escapeHtml(b.note)}</p>`}
function ui(){renderPhases();routeSummary();renderAgents();renderFiles();renderSpec();renderBenchmark()}
function seedAgents(){state.agents={};agent("Architect",state.cfg.architect);agent("Frontend+UX",state.cfg.frontend);agent("Backend",state.cfg.backend);agent("DevOps-X",state.cfg.ops);agent("Adversary",state.cfg.adversary);agent("Verify²",state.cfg.verifier);agent("Image",state.cfg.imageModel)}
async function generateAssets(){const briefs=state.spec?.imageBriefs||[];if(!briefs.length){addEv("Image briefs","PASS","aucune image requise");return}if(!state.cfg.imageBaseUrl){addEv("Image engine","PARTIAL",briefs.length+" image(s) demandée(s), endpoint gratuit non configuré");return}for(const b of briefs){const a=await generateImage(state.cfg,b.prompt);const blob=new Blob([a.bytes],{type:a.mime}),dataUrl=await new Promise((resolve,reject)=>{const fr=new FileReader;fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)});state.assets.push({id:b.id,name:"assets/"+b.id+".png",bytes:a.bytes,dataUrl})}addEv("Image engine","PASS",state.assets.length+" asset(s) généré(s) via endpoint attesté gratuit")}
async function run(){const idea=$("#idea").value.trim();if(!idea)return;setStatus("RUNNING");$("#runBtn").disabled=true;$("#errorBox").classList.add("hidden");state.files=[];state.assets=[];state.evidence=[];state.spec=null;state.bench=null;seedAgents();renderFiles();
 try{
  addEv("Zero-cost text gate",costStatus(state.cfg,"text"),costStatus(state.cfg,"text")==="PASS"?"OpenRouter free router forcé":"endpoint personnalisé: coût non prouvé par ASTRA");
  setPhase("SPEC");agent("Architect",effectiveModel(state.cfg,state.cfg.architect),"RUNNING");state.spec=parse(await chat(state.cfg,state.cfg.architect,prompts.architect,idea));agent("Architect",effectiveModel(state.cfg,state.cfg.architect),"PASS");renderSpec();addEv("Specification","PASS",(state.spec.features?.length||0)+" fonctions, "+(state.spec.acceptance?.length||0)+" critères");
  setPhase("FRONTEND");agent("Frontend+UX",effectiveModel(state.cfg,state.cfg.frontend),"RUNNING");setPhase("BACKEND");agent("Backend",effectiveModel(state.cfg,state.cfg.backend),"RUNNING");agent("DevOps-X",effectiveModel(state.cfg,state.cfg.ops),"RUNNING");const specText=JSON.stringify(state.spec);
  const [frontRaw,backRaw,opsRaw]=await Promise.all([chat(state.cfg,state.cfg.frontend,prompts.frontend,"SPEC:\n"+specText),chat(state.cfg,state.cfg.backend,prompts.backend,"SPEC:\n"+specText),chat(state.cfg,state.cfg.ops,prompts.ops,"SPEC:\n"+specText)]);
  const front=safeFiles(parse(frontRaw)),back=safeFiles(parse(backRaw)),ops=safeFiles(parse(opsRaw));agent("Frontend+UX",effectiveModel(state.cfg,state.cfg.frontend),front.length?"PASS":"FAIL");agent("Backend",effectiveModel(state.cfg,state.cfg.backend),back.length?"PASS":"FAIL");agent("DevOps-X",effectiveModel(state.cfg,state.cfg.ops),ops.length?"PASS":"FAIL");state.files=mergeFiles(front,back,ops);state.selected=state.files[0]?.path||null;renderFiles();selectFile(state.selected);renderPreview();
  setPhase("IMAGES");await generateAssets();renderPreview();renderEvidence();
  setPhase("STATIC TEST");for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail);
  setPhase("ADVERSARY");agent("Adversary",effectiveModel(state.cfg,state.cfg.adversary),"RUNNING");const audit=parse(await chat(state.cfg,state.cfg.adversary,prompts.adversary,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));agent("Adversary",effectiveModel(state.cfg,state.cfg.adversary),audit.risk==="HIGH"?"PARTIAL":"PASS");addEv("Adversarial audit",audit.risk==="HIGH"?"PARTIAL":"PASS",(audit.issues?.length||0)+" issue(s), risk "+audit.risk);
  if((audit.issues?.length||0)>0||state.evidence.some(x=>x.status==="FAIL")){setPhase("REPAIR");const rep=parse(await chat(state.cfg,state.cfg.frontend,prompts.repair,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nAUDIT:\n"+JSON.stringify(audit)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));state.files=mergeFiles(state.files,safeFiles(rep));renderFiles();renderPreview();for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail)}else addEv("Repair loop","PASS","aucune réparation bloquante demandée");
  setPhase("VERIFY²");agent("Verify²",effectiveModel(state.cfg,state.cfg.verifier),"RUNNING");const ver=parse(await chat(state.cfg,state.cfg.verifier,prompts.verify,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)+"\nAUDIT:\n"+JSON.stringify(audit)));agent("Verify²",effectiveModel(state.cfg,state.cfg.verifier),ver.verdict||"PARTIAL");addEv("Verify² independent",ver.verdict||"PARTIAL",ver.summary||"verification terminée");
  state.bench=benchmark(state.files,state.evidence,state.spec);renderBenchmark();const final=state.evidence.some(x=>x.status==="FAIL")?"FAIL":state.evidence.some(x=>x.status==="PARTIAL"||x.status==="UNVERIFIED")||ver.verdict!=="PASS"?"PARTIAL":"PASS";setStatus(final);state.phase="DONE";renderPhases();
 }catch(e){const m=e instanceof Error?e.message:String(e);addEv("Pipeline","FAIL",m);setStatus("FAIL");$("#errorBox").textContent=m;$("#errorBox").classList.remove("hidden")}finally{$("#runBtn").disabled=false}}
function exportZip(){const entries=state.files.map(f=>({name:f.path,bytes:f.content}));for(const a of state.assets)entries.push({name:a.name,bytes:a.bytes});entries.push({name:"astra-evidence.json",bytes:JSON.stringify({generatedAt:new Date().toISOString(),status:state.status,spec:state.spec,evidence:state.evidence,benchmark:state.bench},null,2)});const blob=makeZip(entries),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=(state.spec?.appName||"astra-project").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+".zip";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function saveCfg(){const ids=["baseUrl","apiKey","architect","frontend","backend","ops","adversary","verifier","imageBaseUrl","imageKey","imageModel"];for(const id of ids)state.cfg[id]=$("#"+id).value.trim();state.cfg.zeroCost=$("#zeroCost").checked;state.cfg.attestedFree=$("#attestedFree").checked;sessionStorage.setItem("astra-v2-cfg",JSON.stringify({...state.cfg,apiKey:"",imageKey:""}));routeSummary()}
function loadCfg(){try{state.cfg={...state.cfg,...JSON.parse(sessionStorage.getItem("astra-v2-cfg")||"{}")}}catch{}for(const id of ["baseUrl","architect","frontend","backend","ops","adversary","verifier","imageBaseUrl","imageModel"])$("#"+id).value=state.cfg[id]||"";$("#zeroCost").checked=state.cfg.zeroCost;$("#attestedFree").checked=state.cfg.attestedFree}
$$('[data-preset]').forEach(b=>b.onclick=()=>$("#idea").value=b.dataset.preset);$("#runBtn").onclick=run;$("#exportBtn").onclick=exportZip;$("#settingsBtn").onclick=()=>$("#settingsDialog").showModal();$("#settingsForm").addEventListener("submit",e=>{if(e.submitter?.value!=="cancel")saveCfg()});$("#benchmarkBtn").onclick=()=>{state.bench=benchmark(state.files,state.evidence,state.spec);renderBenchmark();document.querySelector('[data-tab="benchmark"]').click()};$("#downloadFileBtn").onclick=()=>{const f=state.files.find(x=>x.path===state.selected);if(!f)return;const u=URL.createObjectURL(new Blob([f.content],{type:"text/plain"})),a=document.createElement("a");a.href=u;a.download=f.path.split("/").pop();a.click();URL.revokeObjectURL(u)};$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabview').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#view-'+t.dataset.tab).classList.add('active')});
loadCfg();seedAgents();ui();