import{chat,generateImage,effectiveModel,costStatus,normalizeBase}from"./router.js";
import{staticChecks,benchmark}from"./quality.js";
import{makeZip}from"./zip.js";
import{prompts}from"./prompts.js";
import{RescueSupervisor,classifyError,sleep}from"./rescue.js";
import{saveWorkspace,getWorkspace,listWorkspaces,deleteWorkspace,snapshotOf}from"./workspace.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const phases=["SPEC","IMPORT","IMPROVE","FRONTEND","BACKEND","DATABASE","AUTH","OPS","IMAGES","STATIC TEST","SERVER VALIDATE","ADVERSARY","REPAIR","VERIFY²","DEPLOY PLAN"];
const defaults={baseUrl:"https://openrouter.ai/api/v1",apiKey:"",architect:"deepseek/deepseek-v3.2",frontend:"qwen/qwen3-coder-next",backend:"qwen/qwen3-coder-next",ops:"qwen/qwen3-coder-next",adversary:"deepseek/deepseek-v3.2",verifier:"qwen/qwen3.6-plus",imageBaseUrl:"",imageKey:"",imageModel:"black-forest-labs/FLUX.2-klein-4B",zeroCost:true,attestedFree:false,githubToken:"",railwayToken:"",railwayWorkspaceId:"",repoName:"",privateRepo:true};
const state={cfg:{...defaults},files:[],assets:[],spec:null,evidence:[],agents:{},status:"UNVERIFIED",selected:null,bench:null,deployPlan:null,capabilities:null,deployedUrl:"",workspaceId:null,history:[],conversation:[]};
const RESCUE_KEY="astra-rescue-checkpoint-v1";
function saveCheckpoint(label){
 const cp={label,savedAt:new Date().toISOString(),idea:$("#idea")?.value||"",spec:state.spec,files:state.files,evidence:state.evidence,status:state.status,phase:state.phase,bench:state.bench,deployPlan:state.deployPlan,deployedUrl:state.deployedUrl};
 const raw=JSON.stringify(cp);if(raw.length>3500000)throw new Error("checkpoint too large");
 localStorage.setItem(RESCUE_KEY,raw);
}
function restoreCheckpoint(){
 const raw=localStorage.getItem(RESCUE_KEY);if(!raw)return null;const cp=JSON.parse(raw);
 if(cp.idea&&$("#idea"))$("#idea").value=cp.idea;state.spec=cp.spec||state.spec;state.files=Array.isArray(cp.files)?cp.files:state.files;state.evidence=Array.isArray(cp.evidence)?cp.evidence:state.evidence;state.status=cp.status||state.status;state.phase=cp.phase||state.phase;state.bench=cp.bench||state.bench;state.deployPlan=cp.deployPlan||state.deployPlan;state.deployedUrl=cp.deployedUrl||state.deployedUrl;
 renderFiles();renderSpec();renderPreview();renderEvidence();renderBenchmark();setStatus(state.status||"UNVERIFIED");renderPhases();
 return cp;
}
function rescueEvent(e){
 const b=$("#rescueStatus");if(b){b.textContent=e.status==="PASS"?"RESCUE Ω RECOVERED":e.status==="FAIL"?"RESCUE Ω ALERT":"RESCUE Ω WORKING";b.className="badge "+(e.status==="PASS"?"pass":e.status==="FAIL"?"fail":"partial")}
 addEv("ASTRA RESCUE Ω",e.status,e.type+" · "+e.detail);
}
const rescue=new RescueSupervisor({onEvent:rescueEvent,checkpoint:saveCheckpoint,restore:restoreCheckpoint,maxAttempts:3,maxRestarts:2});
async function rescueChat(cfg,model,system,user){return rescue.run("AI "+model,()=>chat(cfg,model,system,user),{attempts:3})}
async function rescueImage(cfg,prompt){return rescue.run("IMAGE",()=>generateImage(cfg,prompt),{attempts:3})}
function parse(t){const c=(t||"").trim().replace(/^\`\`\`(?:json)?/i,"").replace(/\`\`\`$/i,"").trim();try{return JSON.parse(c)}catch{}const a=c.indexOf("{"),b=c.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(c.slice(a,b+1));throw new Error("Réponse IA non JSON")}
function safeFiles(v){return(v?.files||[]).filter(x=>x&&typeof x.path==="string"&&typeof x.content==="string"&&x.path&&!x.path.includes("..")&&!x.path.startsWith("/"))}
function mergeFiles(...groups){const m=new Map;for(const g of groups)for(const f of g)m.set(f.path,f);return[...m.values()].sort((a,b)=>a.path.localeCompare(b.path))}
function setStatus(s){state.status=s;const e=$("#globalStatus");e.textContent=s;e.className="badge "+s.toLowerCase()}
function setPhase(name){if(state.phase&&state.phase!==name)rescue.checkpoint("phase:"+state.phase);state.phase=name;renderPhases()}
function renderPhases(){const root=$("#phases");root.innerHTML=phases.map((p,i)=>`<div class="phase ${state.phase===p?"active":""}"><b>${i+1}</b><span>${p}</span><em>${state.phase===p?"RUNNING":state.phase==="DONE"?"DONE":"WAIT"}</em></div>`).join("")}
function agent(name,model,status="UNVERIFIED"){state.agents[name]={model,status};renderAgents()}
function renderAgents(){const r=$("#agents");r.innerHTML=Object.entries(state.agents).map(([n,a])=>`<div class="agent"><span>${n}</span><small>${a.model}</small><small class="${a.status.toLowerCase()}">${a.status}</small></div>`).join("")}
function addEv(name,status,detail){const i=state.evidence.findIndex(x=>x.name===name);const x={name,status,detail};if(i>=0)state.evidence[i]=x;else state.evidence.push(x);renderEvidence()}
function renderEvidence(){const r=$("#ledger");r.innerHTML=state.evidence.length?state.evidence.map(x=>`<div class="ev"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.detail)}</small></div><span class="${x.status.toLowerCase()}">${x.status}</span></div>`).join(""):'<p class="muted">Aucun contrôle exécuté.</p>';const p=state.evidence.filter(x=>x.status==="PASS").length;$("#score").textContent=p+"/"+state.evidence.length;$("#fileCount").textContent=state.files.length;$("#assetCount").textContent=state.assets.length;$("#testCount").textContent=state.files.filter(f=>/(test|spec)/i.test(f.path)).length;$("#deployReadiness").textContent=state.evidence.some(x=>x.status==="FAIL")?"FAIL":state.files.some(f=>f.path==="deploy.json")?"PARTIAL":"UNVERIFIED"}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function routeSummary(){const c=state.cfg;$("#routeSummary").innerHTML=`ZERO-COST GATE: <b>${c.zeroCost?"ON":"OFF"}</b><br>Text: ${escapeHtml(normalizeBase(c.baseUrl)||"—")}<br>Builder effectif: ${escapeHtml(effectiveModel(c,c.frontend))}<br>Text cost gate: <b>${costStatus(c,"text")}</b> · Image cost gate: <b>${costStatus(c,"image")}</b>`}
function renderFiles(){const tree=$("#fileTree");tree.innerHTML=state.files.map(f=>`<button data-path="${escapeHtml(f.path)}" class="${state.selected===f.path?"active":""}" title="${escapeHtml(f.path)}">${escapeHtml(f.path)}</button>`).join("");$("#fileTree button").forEach(b=>b.onclick=()=>selectFile(b.dataset.path));$("#exportBtn").disabled=!state.files.length;$("#deployBtn").disabled=!(state.files.length&&state.capabilities?.deployBroker);$("#improveBtn").disabled=!state.files.length;renderEvidence()}
function selectFile(path){state.selected=path;const f=state.files.find(x=>x.path===path);$("#filePath").textContent=path||"—";$("#codeViewer").textContent=f?.content||"";$("#downloadFileBtn").disabled=!f;renderFiles()}
function previewDoc(){const m=Object.fromEntries(state.files.map(f=>[f.path,f.content]));let h=m["preview/index.html"]||"<html><body><h1>Preview absente</h1></body></html>";h=h.replace(/<link[^>]*href=["'](?:\.\/)?styles\.css["'][^>]*>/i,"<style>"+(m["preview/styles.css"]||"").replace(/<\/style/gi,"<\\/style")+"</style>");h=h.replace(/<script[^>]*src=["'](?:\.\/)?app\.js["'][^>]*><\/script>/i,"<script>"+(m["preview/app.js"]||"").replace(/<\/script/gi,"<\\/script")+"<\\/script>");for(const a of state.assets){h=h.replace(new RegExp(`(<img[^>]*data-astra-image=["']${a.id}["'][^>]*)(>)`,"gi"),`$1 src="${a.dataUrl}"$2`)}return h}
function renderPreview(){const f=$("#preview"),empty=$("#previewEmpty");if(state.files.some(x=>x.path==="preview/index.html")){f.style.display="block";empty.classList.add("hidden");f.srcdoc=previewDoc()}else{f.style.display="none";empty.classList.remove("hidden")}}
function renderSpec(){$("#specViewer").textContent=JSON.stringify(state.spec||{status:"waiting"},null,2)}
function renderBenchmark(){const b=state.bench;if(!b){$("#benchmarkView").innerHTML="<p>Aucun benchmark exécuté.</p>";return}$("#benchmarkView").innerHTML=`<div class="bench-grid"><div class="bench-card"><small>Evidence quality</small><b>${b.quality}%</b></div><div class="bench-card"><small>Completeness</small><b>${b.completeness}%</b></div><div class="bench-card"><small>Architecture</small><b>${b.architecture}%</b></div></div><table class="bench-table"><tr><th>Mesure</th><th>ASTRA</th><th>Lovable</th><th>Bolt</th></tr><tr><td>Files</td><td>${b.files}</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr><tr><td>Tests</td><td>${b.tests}</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr><tr><td>Résultat comparatif</td><td>Mesuré localement</td><td>UNVERIFIED</td><td>UNVERIFIED</td></tr></table><p class="muted">${escapeHtml(b.note)}</p>`}
async function persistWorkspace(message){
 try{const record=await saveWorkspace(snapshotOf({...state,idea:$("#idea")?.value||"",history:state.history,conversation:state.conversation},message));
 state.workspaceId=record.id;state.history=record.history||[];state.conversation=record.conversation||[];
 addEv("Workspace","PASS","saved "+record.id.slice(0,8)+" · "+message);await renderWorkspaceList();return record}
 catch(e){addEv("Workspace","PARTIAL","local persistence unavailable: "+String(e?.message||e));return null}
}
async function renderWorkspaceList(){
 const root=$("#workspaceList");if(!root)return;const items=await listWorkspaces();
 root.innerHTML=items.length?items.map(x=>`<div class="workspace-item"><div><b>${escapeHtml(x.name||"Untitled")}</b><small>${escapeHtml(x.updatedAt||"")} · ${(x.files||[]).length} files</small></div><div><button class="btn tiny" data-open="${x.id}">Open</button><button class="btn tiny ghost" data-delete="${x.id}">Delete</button></div></div>`).join(""):'<p class="muted">Aucun projet sauvegardé.</p>';
 root.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>loadWorkspaceById(b.dataset.open));root.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{await deleteWorkspace(b.dataset.delete);await renderWorkspaceList()});
}
async function loadWorkspaceById(id){
 const p=await getWorkspace(id);if(!p)return;state.workspaceId=p.id;state.spec=p.spec||null;state.files=p.files||[];state.evidence=p.evidence||[];state.bench=p.bench||null;state.deployPlan=p.deployPlan||null;state.deployedUrl=p.deployedUrl||"";state.history=p.history||[];state.conversation=p.conversation||[];$("#idea").value=p.idea||"";state.selected=state.files[0]?.path||null;renderFiles();renderSpec();renderPreview();renderEvidence();renderBenchmark();setStatus(state.evidence.some(x=>x.status==="FAIL")?"FAIL":"PARTIAL");$("#workspaceDialog").close();rescue.checkpoint("workspace-open:"+id);
}
async function auditRepairVerify(context){
 setPhase("STATIC TEST");for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail);await serverValidate();
 setPhase("ADVERSARY");const audit=parse(await rescueChat(state.cfg,state.cfg.adversary,prompts.adversary,"CONTEXT:\n"+context+"\nSPEC:\n"+JSON.stringify(state.spec)+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));addEv("Adversarial audit",audit.risk==="HIGH"?"PARTIAL":"PASS",(audit.issues?.length||0)+" issue(s), risk "+audit.risk);
 if((audit.issues?.length||0)>0||state.evidence.some(x=>x.status==="FAIL")){setPhase("REPAIR");const rep=parse(await rescueChat(state.cfg,state.cfg.frontend,prompts.repair,"CONTEXT:\n"+context+"\nSPEC:\n"+JSON.stringify(state.spec)+"\nFILES:\n"+JSON.stringify(state.files)+"\nAUDIT:\n"+JSON.stringify(audit)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));state.files=mergeFiles(state.files,safeFiles(rep));renderFiles();renderPreview();for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail);await serverValidate()}
 setPhase("VERIFY²");const ver=parse(await rescueChat(state.cfg,state.cfg.verifier,prompts.verify,"CONTEXT:\n"+context+"\nSPEC:\n"+JSON.stringify(state.spec)+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)+"\nAUDIT:\n"+JSON.stringify(audit)));addEv("Verify² independent",ver.verdict||"PARTIAL",ver.summary||"verification terminée");await buildDeployPlan();const final=state.evidence.some(x=>x.status==="FAIL")?"FAIL":state.evidence.some(x=>x.status==="PARTIAL"||x.status==="UNVERIFIED")||ver.verdict!=="PASS"?"PARTIAL":"PASS";setStatus(final);state.phase="DONE";renderPhases();return ver;
}
async function improveCurrent(){
 const request=$("#improveInput").value.trim();if(!request||!state.files.length)return;$("#improveDialog").close();setStatus("RUNNING");setPhase("IMPROVE");rescue.checkpoint("before-improve");state.conversation.push({at:new Date().toISOString(),role:"user",content:request});
 try{state.spec=parse(await rescueChat(state.cfg,state.cfg.architect,prompts.evolveSpec,"REQUEST:\n"+request+"\nCURRENT SPEC:\n"+JSON.stringify(state.spec)));renderSpec();const out=parse(await rescueChat(state.cfg,state.cfg.frontend,prompts.improve,"REQUEST:\n"+request+"\nSPEC:\n"+JSON.stringify(state.spec)+"\nFILES:\n"+JSON.stringify(state.files)+"\nEVIDENCE:\n"+JSON.stringify(state.evidence)));const patch=safeFiles(out);if(!patch.length)throw new Error("Improve Ω returned no file changes");state.files=mergeFiles(state.files,patch);state.conversation.push({at:new Date().toISOString(),role:"assistant",content:out.summary||"Patch applied"});addEv("Improve with Ω","PASS",patch.length+" file(s) changed · "+(out.summary||""));renderFiles();renderPreview();await auditRepairVerify("Improve request: "+request);await persistWorkspace("Improve Ω: "+request.slice(0,100));rescue.checkpoint("improve-complete")}
 catch(e){const d=classifyError(e);addEv("Improve with Ω","FAIL",d.kind+" · "+String(e?.message||e));setStatus("FAIL")}
}
async function importGithub(){
 const repo=$("#importRepo").value.trim(),ref=$("#importRef").value.trim()||"main";if(!repo)return;if(!state.cfg.githubToken){$("#workspaceDialog").close();$("#settingsDialog").showModal();addEv("GitHub import","UNVERIFIED","GitHub token required in Cloud models");return}
 setStatus("RUNNING");setPhase("IMPORT");state.evidence=[];state.files=[];state.assets=[];state.workspaceId=null;state.history=[];state.conversation=[{at:new Date().toISOString(),role:"user",content:"Import "+repo+" @ "+ref}];renderEvidence();
 try{const r=await control("/api/import_github",{githubToken:state.cfg.githubToken,repo,ref});if(!r.data?.files?.length)throw new Error(r.data?.reason||"No files imported");state.files=r.data.files;const reversePayload=state.files.slice(0,70).map(f=>({path:f.path,excerpt:f.content.slice(0,2200)}));state.spec=parse(await rescueChat(state.cfg,state.cfg.architect,prompts.reverseArchitect,"REPOSITORY: "+repo+" @ "+ref+"\nFILES:\n"+JSON.stringify(reversePayload)));$("#idea").value="Imported from GitHub: "+repo;state.selected=state.files[0]?.path||null;addEv("GitHub import","PASS",r.data.stats.files+" files · "+r.data.stats.bytes+" bytes"+(r.data.stats.truncated?" · truncated":""));renderFiles();renderSpec();renderPreview();await auditRepairVerify("Imported existing application "+repo+" @ "+ref);await persistWorkspace("Imported "+repo+" @ "+ref);$("#workspaceDialog").close();rescue.checkpoint("import-complete")}
 catch(e){addEv("GitHub import","FAIL",String(e?.message||e));setStatus("FAIL")}
}
function ui(){renderPhases();routeSummary();renderAgents();renderFiles();renderSpec();renderBenchmark()}
function seedAgents(){state.agents={};agent("Architect",state.cfg.architect);agent("Frontend+UX",state.cfg.frontend);agent("Backend",state.cfg.backend);agent("Database",state.cfg.backend);agent("Auth+Security",state.cfg.backend);agent("DevOps-X",state.cfg.ops);agent("Adversary",state.cfg.adversary);agent("Verify²",state.cfg.verifier);agent("Image",state.cfg.imageModel)}
async function generateAssets(){const briefs=state.spec?.imageBriefs||[];if(!briefs.length){addEv("Image briefs","PASS","aucune image requise");return}if(!state.cfg.imageBaseUrl){addEv("Image engine","PARTIAL",briefs.length+" image(s) demandée(s), endpoint gratuit non configuré");return}for(const b of briefs){const a=await rescueImage(state.cfg,b.prompt);const blob=new Blob([a.bytes],{type:a.mime}),dataUrl=await new Promise((resolve,reject)=>{const fr=new FileReader;fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)});state.assets.push({id:b.id,name:"assets/"+b.id+".png",bytes:a.bytes,dataUrl})}addEv("Image engine","PASS",state.assets.length+" asset(s) généré(s) via endpoint attesté gratuit")}
async function control(path,payload){return rescue.run("CONTROL "+path,async()=>{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data={raw}};if(!r.ok&&r.status!==501)throw new Error("Control plane "+r.status+": "+raw.slice(0,220));return{ok:r.ok,status:r.status,data}},{attempts:3})}
async function serverValidate(){setPhase("SERVER VALIDATE");const r=await control("/api/validate",{spec:state.spec,files:state.files});for(const e of r.data.evidence||[])addEv("Server · "+e.name,e.status,e.detail);addEv("Server validation",r.data.verdict||"UNVERIFIED",r.data.summary||"control plane response");return r.data}
async function buildDeployPlan(){setPhase("DEPLOY PLAN");const r=await control("/api/deploy-plan",{spec:state.spec,files:state.files});state.deployPlan=r.data;const st=r.data?.status||"UNVERIFIED";addEv("Deploy plan",st,r.data?.note||"plan generated");$("#deployReadiness").textContent=st;return r.data}
async function deployGenerated(){
 if(!state.files.length)return;
 if(!state.cfg.githubToken||!state.cfg.railwayToken){addEv("Generated app deployment","UNVERIFIED","GitHub/Railway credentials missing");$("#settingsDialog").showModal();return}
 $("#deployBtn").disabled=true;addEv("Generated app deployment","PARTIAL","GitHub push + Railway deployment starting");
 try{
  const r=await control("/api/deploy",{spec:state.spec,files:state.files,deploy:{githubToken:state.cfg.githubToken,railwayToken:state.cfg.railwayToken,railwayWorkspaceId:state.cfg.railwayWorkspaceId,repoName:state.cfg.repoName,privateRepo:state.cfg.privateRepo}});
  const rw=r.data?.railway,git=r.data?.git;if(!rw?.deploymentId)throw new Error(r.data?.reason||"Deployment ID missing");
  addEv("GitHub commit","PASS",(git?.fullName||"repo")+" @ "+String(git?.commitSha||"").slice(0,8));
  addEv("Railway deployment","PARTIAL","deployment "+rw.deploymentId);
  $("#deployReadiness").textContent="PARTIAL";
  for(let i=0;i<30;i++){
   await new Promise(resolve=>setTimeout(resolve,4000));
   const s=await control("/api/deploy_status",{railwayToken:state.cfg.railwayToken,deploymentId:rw.deploymentId,domain:rw.domain,healthPath:rw.healthPath});
   addEv("Railway deployment",s.data?.status||"PARTIAL",(s.data?.deploymentStatus||"UNKNOWN")+" · health "+(s.data?.health?.status||"UNVERIFIED"));
   if(s.data?.status==="PASS"){state.deployedUrl="https://"+rw.domain;addEv("Public health gate","PASS",state.deployedUrl+(rw.healthPath||"/health"));$("#deployReadiness").textContent="PASS";setStatus("PASS");alert("Déploiement vérifié : "+state.deployedUrl);break}
   if(s.data?.status==="FAIL"){addEv("Public health gate","FAIL",s.data?.health?.error||"deployment failed");$("#deployReadiness").textContent="FAIL";setStatus("FAIL");break}
  }
  if(!state.deployedUrl&&$("#deployReadiness").textContent!=="FAIL")addEv("Public health gate","UNVERIFIED","timeout before verified 2xx health response");
 }catch(e){addEv("Generated app deployment","FAIL",e instanceof Error?e.message:String(e));$("#deployReadiness").textContent="FAIL";setStatus("FAIL")}
 finally{$("#deployBtn").disabled=!(state.files.length&&state.capabilities?.deployBroker)}
}
async function loadCapabilities(){try{const r=await fetch("/api/capabilities");state.capabilities=await r.json();addEv("Control plane","PASS","server v"+state.capabilities.version+", validation active");addEv("Deploy broker",state.capabilities.deployBroker?"PASS":"UNVERIFIED",state.capabilities.nativeDeployBroker?"GitHub + Railway native broker ready":"broker unavailable");renderFiles()}catch{addEv("Control plane","FAIL","/api/capabilities inaccessible")}}
async function run(rescueCycle=0){const idea=$("#idea").value.trim();if(!idea)return;if(rescueCycle===0){state.workspaceId=null;state.history=[];state.conversation=[{at:new Date().toISOString(),role:"user",content:idea}]}setStatus("RUNNING");$("#runBtn").disabled=true;$("#errorBox").classList.add("hidden");state.files=[];state.assets=[];state.evidence=[];state.spec=null;state.bench=null;seedAgents();renderFiles();
 try{
  addEv("Zero-cost text gate",costStatus(state.cfg,"text"),costStatus(state.cfg,"text")==="PASS"?"OpenRouter free router forcé":"endpoint personnalisé: coût non prouvé par ASTRA");
  setPhase("SPEC");agent("Architect",effectiveModel(state.cfg,state.cfg.architect),"RUNNING");state.spec=parse(await rescueChat(state.cfg,state.cfg.architect,prompts.architect,idea));agent("Architect",effectiveModel(state.cfg,state.cfg.architect),"PASS");renderSpec();addEv("Specification","PASS",(state.spec.features?.length||0)+" fonctions, "+(state.spec.acceptance?.length||0)+" critères");
  setPhase("FRONTEND");agent("Frontend+UX",effectiveModel(state.cfg,state.cfg.frontend),"RUNNING");agent("Backend",effectiveModel(state.cfg,state.cfg.backend),"RUNNING");agent("Database",effectiveModel(state.cfg,state.cfg.backend),"RUNNING");agent("Auth+Security",effectiveModel(state.cfg,state.cfg.backend),"RUNNING");agent("DevOps-X",effectiveModel(state.cfg,state.cfg.ops),"RUNNING");const specText=JSON.stringify(state.spec);
  const [frontRaw,backRaw,dbRaw,authRaw,opsRaw]=await Promise.all([rescueChat(state.cfg,state.cfg.frontend,prompts.frontend,"SPEC:\n"+specText),rescueChat(state.cfg,state.cfg.backend,prompts.backend,"SPEC:\n"+specText),rescueChat(state.cfg,state.cfg.backend,prompts.database,"SPEC:\n"+specText),rescueChat(state.cfg,state.cfg.backend,prompts.auth,"SPEC:\n"+specText),rescueChat(state.cfg,state.cfg.ops,prompts.ops,"SPEC:\n"+specText)]);
  const front=safeFiles(parse(frontRaw)),back=safeFiles(parse(backRaw)),db=safeFiles(parse(dbRaw)),auth=safeFiles(parse(authRaw)),ops=safeFiles(parse(opsRaw));agent("Frontend+UX",effectiveModel(state.cfg,state.cfg.frontend),front.length?"PASS":"FAIL");agent("Backend",effectiveModel(state.cfg,state.cfg.backend),back.length?"PASS":"FAIL");agent("Database",effectiveModel(state.cfg,state.cfg.backend),db.length?"PASS":"FAIL");agent("Auth+Security",effectiveModel(state.cfg,state.cfg.backend),auth.length?"PASS":"FAIL");agent("DevOps-X",effectiveModel(state.cfg,state.cfg.ops),ops.length?"PASS":"FAIL");state.files=mergeFiles(front,back,db,auth,ops);state.selected=state.files[0]?.path||null;renderFiles();selectFile(state.selected);renderPreview();
  setPhase("IMAGES");await generateAssets();renderPreview();renderEvidence();
  setPhase("STATIC TEST");for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail);await serverValidate();
  setPhase("ADVERSARY");agent("Adversary",effectiveModel(state.cfg,state.cfg.adversary),"RUNNING");const audit=parse(await rescueChat(state.cfg,state.cfg.adversary,prompts.adversary,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));agent("Adversary",effectiveModel(state.cfg,state.cfg.adversary),audit.risk==="HIGH"?"PARTIAL":"PASS");addEv("Adversarial audit",audit.risk==="HIGH"?"PARTIAL":"PASS",(audit.issues?.length||0)+" issue(s), risk "+audit.risk);
  if((audit.issues?.length||0)>0||state.evidence.some(x=>x.status==="FAIL")){setPhase("REPAIR");const rep=parse(await rescueChat(state.cfg,state.cfg.frontend,prompts.repair,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nAUDIT:\n"+JSON.stringify(audit)+"\nCHECKS:\n"+JSON.stringify(state.evidence)));state.files=mergeFiles(state.files,safeFiles(rep));renderFiles();renderPreview();for(const e of staticChecks(state.files,state.spec))addEv(e.name,e.status,e.detail)}else addEv("Repair loop","PASS","aucune réparation bloquante demandée");
  setPhase("VERIFY²");agent("Verify²",effectiveModel(state.cfg,state.cfg.verifier),"RUNNING");const ver=parse(await rescueChat(state.cfg,state.cfg.verifier,prompts.verify,"SPEC:\n"+specText+"\nFILES:\n"+JSON.stringify(state.files)+"\nCHECKS:\n"+JSON.stringify(state.evidence)+"\nAUDIT:\n"+JSON.stringify(audit)));agent("Verify²",effectiveModel(state.cfg,state.cfg.verifier),ver.verdict||"PARTIAL");addEv("Verify² independent",ver.verdict||"PARTIAL",ver.summary||"verification terminée");
  await buildDeployPlan();state.bench=benchmark(state.files,state.evidence,state.spec);renderBenchmark();const final=state.evidence.some(x=>x.status==="FAIL")?"FAIL":state.evidence.some(x=>x.status==="PARTIAL"||x.status==="UNVERIFIED")||ver.verdict!=="PASS"?"PARTIAL":"PASS";setStatus(final);state.phase="DONE";renderPhases();await persistWorkspace("Initial generation");rescue.checkpoint("pipeline-complete");rescue.clearRestartCounter();
 }catch(e){const m=e instanceof Error?e.message:String(e),d=classifyError(e);rescue.checkpoint("pipeline-error:"+d.kind);
  if(d.retryable&&rescueCycle<2){rescue.emit("PIPELINE_RESTART","PARTIAL",d.kind+" · restart "+(rescueCycle+1)+"/2");await sleep(900*Math.pow(2,rescueCycle));return await run(rescueCycle+1)}
  rescue.emit("CIRCUIT_BREAKER","FAIL",d.kind+" · "+m);addEv("Pipeline","FAIL",m);setStatus("FAIL");$("#errorBox").textContent="ASTRA RESCUE Ω a arrêté les retries pour éviter une boucle : "+m;$("#errorBox").classList.remove("hidden")
 }finally{$("#runBtn").disabled=false}}
function exportZip(){const entries=state.files.map(f=>({name:f.path,bytes:f.content}));for(const a of state.assets)entries.push({name:a.name,bytes:a.bytes});entries.push({name:"astra-evidence.json",bytes:JSON.stringify({generatedAt:new Date().toISOString(),status:state.status,spec:state.spec,evidence:state.evidence,benchmark:state.bench},null,2)});const blob=makeZip(entries),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=(state.spec?.appName||"astra-project").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+".zip";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function saveCfg(){const ids=["baseUrl","apiKey","architect","frontend","backend","ops","adversary","verifier","imageBaseUrl","imageKey","imageModel","githubToken","railwayToken","railwayWorkspaceId","repoName"];for(const id of ids)state.cfg[id]=$("#"+id).value.trim();state.cfg.zeroCost=$("#zeroCost").checked;state.cfg.attestedFree=$("#attestedFree").checked;state.cfg.privateRepo=$("#privateRepo").checked;sessionStorage.setItem("astra-v3-cfg",JSON.stringify({...state.cfg,apiKey:"",imageKey:"",githubToken:"",railwayToken:""}));routeSummary();renderFiles()}
function loadCfg(){try{state.cfg={...state.cfg,...JSON.parse(sessionStorage.getItem("astra-v3-cfg")||"{}")}}catch{}for(const id of ["baseUrl","architect","frontend","backend","ops","adversary","verifier","imageBaseUrl","imageModel","railwayWorkspaceId","repoName"])$("#"+id).value=state.cfg[id]||"";$("#apiKey").value="";$("#imageKey").value="";$("#githubToken").value="";$("#railwayToken").value="";$("#zeroCost").checked=state.cfg.zeroCost;$("#attestedFree").checked=state.cfg.attestedFree;$("#privateRepo").checked=state.cfg.privateRepo!==false}
$$('[data-preset]').forEach(b=>b.onclick=()=>$("#idea").value=b.dataset.preset);$("#runBtn").onclick=run;$("#exportBtn").onclick=exportZip;$("#deployPlanBtn").onclick=buildDeployPlan;$("#deployBtn").onclick=deployGenerated;$("#projectsBtn").onclick=async()=>{await renderWorkspaceList();$("#workspaceDialog").showModal()};$("#improveBtn").onclick=()=>$("#improveDialog").showModal();$("#applyImproveBtn").onclick=improveCurrent;$("#cancelImproveBtn").onclick=()=>$("#improveDialog").close();$("#closeImproveBtn").onclick=()=>$("#improveDialog").close();$("#closeWorkspaceBtn").onclick=()=>$("#workspaceDialog").close();$("#importRepoBtn").onclick=importGithub;$("#settingsBtn").onclick=()=>$("#settingsDialog").showModal();$("#settingsForm").addEventListener("submit",e=>{if(e.submitter?.value!=="cancel")saveCfg()});$("#benchmarkBtn").onclick=()=>{state.bench=benchmark(state.files,state.evidence,state.spec);renderBenchmark();document.querySelector('[data-tab="benchmark"]').click()};$("#downloadFileBtn").onclick=()=>{const f=state.files.find(x=>x.path===state.selected);if(!f)return;const u=URL.createObjectURL(new Blob([f.content],{type:"text/plain"})),a=document.createElement("a");a.href=u;a.download=f.path.split("/").pop();a.click();URL.revokeObjectURL(u)};$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabview').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#view-'+t.dataset.tab).classList.add('active')});
loadCfg();seedAgents();ui();const recovered=rescue.restore();if(recovered)rescue.emit("RESTORE","PASS","checkpoint "+(recovered.label||"unknown")+" restored");rescue.installGlobal({restart:()=>location.reload()});renderWorkspaceList().catch(e=>addEv("Workspace","PARTIAL",String(e?.message||e)));loadCapabilities();